baseURL = ""
languageCode = "en-us"
defaultContentLanguage = "zh-cn"
publishDir = "docs"
title = "Leopord的博客"
theme = "m10c"
paginate = 5

[params]
  author = "Leopord"
  description = ""
  avatar = "/img/avatar.jpg"
  [[params.social]]
    name = "github"
    url = "https://github.com/leopord"
